# org.kecak.jwtSecret can be sent from java environment variable
# using additional argument
# for example : java -Dorg.kecak.jwtSecret=This\ is\ very\ secret
jwt.secret=${org.kecak.jwtSecret:It's not secure to use default key}
jwt.expirationRefreshToken=300